# Generated by Django 5.1.6 on 2025-04-04 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transport',
            old_name='destination',
            new_name='arrival_city',
        ),
        migrations.AddField(
            model_name='transport',
            name='departure_city',
            field=models.CharField(default='VilleDefaut', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='transport',
            name='classe',
            field=models.CharField(choices=[('commun', 'Commun'), ('vip', 'VIP'), ('luxe', 'Luxe')], default='commun', max_length=10),
        ),
        migrations.AlterField(
            model_name='transport',
            name='type',
            field=models.CharField(choices=[('minibus', 'Minibus'), ('microbus', 'Microbus'), ('standard_bus', 'Bus standard'), ('coach_bus', 'Bus grand tourisme'), ('articulated_bus', 'Bus articulé'), ('double_decker', 'Bus à étage'), ('autre', 'Autre type de bus')], default='minibus', max_length=20),
        ),
    ]
