# Generated by Django 5.1.6 on 2025-04-04 23:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0002_rename_destination_transport_arrival_city_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='reservation',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='transport.reservation'),
        ),
        migrations.AlterField(
            model_name='transport',
            name='classe',
            field=models.CharField(choices=[('commun', 'Commun'), ('vip', 'VIP'), ('luxe', 'Luxe'), ('standard', 'Standard')], default='commun', max_length=10),
        ),
        migrations.AlterField(
            model_name='transport',
            name='type',
            field=models.CharField(choices=[('minibus', 'Minibus'), ('microbus', 'Microbus'), ('urbain', 'Urbain'), ('coach_bus', 'Bus grand tourisme'), ('articulated_bus', 'Bus articulé'), ('double_decker', 'Bus à étage'), ('autre', 'Autre type de bus')], default='minibus', max_length=20),
        ),
    ]
